config/routes.rb
Rails.application.routes.draw do
  
  get 'reservations/index'
  #get 'rooms/index'
  #get 'users/home'
  root 'users#home'
  
  devise_for :users, 
              path: '', 
              path_names: {sign_up: 'register', sign_in: 'login', edit: 'account', sign_out: 'logout'},
              controllers: {registrations: 'registrations'}

  resources :users do
    collection do
      get 'profile'
      get 'account'
    end
  end


  resources :rooms do
    collection do
      get 'own'
      get 'search'
    end
  end

  resources :reservations do
    collection do
      post 'confirm' ,to: 'reservations#confirm'
    end
    member do
      patch 'edit_confirm'
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :user
    belongs_to :room

    validates :check_in, presence: true
    validates :check_out, presence: true
    validates :pepole, presence: true

    validate :date_before_finish

    def date_before_finish
        return if check_out.blank? || check_in.blank?
        errors.add(:check_out, "はチェックイン日より後の日付となるよう選択してください") unless
        self.check_in <= self.check_out
    end

    def days
        (check_out - check_in).to_i
    end

    def total_price
        room.price * pepole * days
    end

end

app/models/room.rb
class Room < ApplicationRecord
    belongs_to :user
    has_many :reservations,dependent: :destroy

    mount_uploader :facility_img, FacilityUploader

    validates :facility_name, presence: true
    validates :facility_detail, presence: true
    validates :price, presence: true
    validates :address, presence: true
    

end

app/models/user.rb
class User < ApplicationRecord

  has_many :rooms
  has_many :reservations

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  validates :full_name, presence: true, length: {maximum: 50}

  mount_uploader :avatar, AvatarUploader

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:full_name])
        devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar])
    end
    
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    protected
    def update_resource(resource, params)
        resource.update_without_password(params)
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  
  def index
    @room = Room.all
    @reservation = Reservation.where(user_id: current_user.id)
  end

  def new
    @room = Room.find(params[:id])
    @reservation = Reservation.new(reservation_params)
  end

  def confirm
    @room = Room.find(params[:reservation][:room_id])
    @reservation = Reservation.new(reservation_params)
    unless @reservation.valid?
      render template: "rooms/show"
    end
  end

  def create
    @room = Room.find(params[:reservation][:room_id])
    @reservation = Reservation.new(reservation_params)
    render room_path(@room) and return if !@reservation.save
    redirect_to "/reservations"
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end

  def edit_confirm
    @reservation = Reservation.find(params[:id])
    @reservation.attributes = reservation_params
    render :edit if @reservation.invalid?
  end

  def update
    @reservation = Reservation.find(params[:id])
    if @reservation.update(reservation_params)
      flash[:notice] = "施設名「#{@reservation.room.facility_name}」の情報を更新しました"
      redirect_to "/reservations"
    else
      flash[:alert] = "施設情報の更新に失敗しました"
      render "edit"
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    flash[:notice] = "ユーザーを削除しました"
    redirect_to "/reservations"
  end

  private
  def reservation_params
    params.require(:reservation).permit(:check_in,:check_out,:pepole, :user_id, :room_id)
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :search

  def index
    @rooms = Room.all
  end

  def new
    @user = current_user.id
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id
    if @room.save
      flash[:notice] = "新規施設の登録をしました"
      redirect_to "/rooms/own"
    else
      render "new"
    end
  end

  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new
  end

  def own
    @rooms = Room.where(user_id: current_user.id)
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    if @room.update(room_params)
      flash[:notice] = "タイトル「#{@room.facility_name}」の情報を更新しました"
      redirect_to "/rooms/own"
    else
      flash[:alert] = "施設情報の更新に失敗しました"
      render "edit"
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    flash[:notice] = "「#{@room.facility_name}」を削除しました"
    redirect_to "/rooms/own"
  end

  def search
    @q = Room.ransack(params[:q])
    @rooms = @q.result(distinct: true)
  end

  private
  def room_params
    params.require(:room).permit(:facility_name, :facility_detail, :price, :address, :facility_img, :user_id)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :search

  def home
  end

  def search
    @q = Room.ransack(params[:q])
    @rooms = @q.result(distinct: true)
  end

  def profile
    @user = User.all
  end

  def account
    @user = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "タイトル「#{current_user.id}」の情報を更新しました"
      redirect_to "/users/profile"
    else
      flash[:alert] = "施設情報の更新に失敗しました"
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:avatar, :full_name, :introduction, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StayReserve</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    
    <%= render  "shared/navbar" %>
    <%= render "shared/notification" %>

    <%= yield %>
  
  <footer>
    <div class="container-fluid">
      <p>
        Copyright © Stay Reserve 2023 All rights reserved
      </p>
    </div>
  </footer>
  </body>
</html>

app/views/reservations/confirm.html.erb
<div class="container reservation_form">
  <h2>予約内容の確認</h2>
  <table class="confirm_table">
    <tr>
      <th>チェックイン</th>
      <td><%= @reservation.check_in.strftime('%Y/%m/%d') %></td>
    </tr>
    <tr>
      <th>チェックアウト</th>
      <td><%= @reservation.check_out.strftime('%Y/%m/%d') %></td>
    </tr>
    <tr>
      <th>日数</th>
      <td><%= @reservation.days %></td>
    </tr>
    <tr>
      <th>宿泊人数</th>
      <td><%= @reservation.pepole %></td>
    </tr>
    <tr>
      <th>お支払い金額</th>
      <td>¥<%= @reservation.total_price.to_s(:delimited) %></td>
    </tr>
  </table>
  <p class="cofirm_info">上記内容で正しければ「確定」ボタンを押してください。</p>
  <%= form_with model:@reservation do |f| %>
    <%= f.hidden_field :check_in, value: @reservation.check_in %>
    <%= f.hidden_field :check_out, value: @reservation.check_out %>
    <%= f.hidden_field :pepole, value: @reservation.pepole %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :room_id, value: @room.id %>
    <div class="filed">
      <%= f.submit '確定', class: "button is-danger btn" %>
    </div>
    <div class="actions">
      <%= link_to"キャンセル",room_path(@room), class: "button m-t-10 btn"  %>
    </div>
  <% end %>
</div>

app/views/reservations/edit.html.erb
<div class="container">
    <section>
        <div class="re_resrvation_form">
            <div class="title">
                <h2>再予約する</h2>
            </div> 
            <%= render "shared/error", obj: @reservation %>
            <div class="register_form">
                <%=  image_tag @reservation.room.facility_img.url,class: "room_img"  %>
                <div class="room_title">
                    <h2><%= @reservation.room.facility_name %></h2>
                    <p class="room_price">¥<%= @reservation.room.price.to_s(:delimited) %>〜</p>
                </div>
                <p><%= @reservation.room.address %></p>
                <p class="room_facility_detail"><%= @reservation.room.facility_detail %></p>
                <%= form_with model: @reservation, url: edit_confirm_reservation_path(@reservation) do |f| %>
                    <div class="form_label">
                        <%= f.label :check_in ,"チェックイン", class:"Required"  %>
                        <%= f.date_field :check_in, class: "input is-link", placeholder: "---- / -- / --" %>
                    </div>
                    <div class="form_label">
                        <%= f.label :check_out ,"チェックアウト", class:"Required"  %>
                        <%= f.date_field :check_out, class: "input is-link", placeholder: "---- / -- / --" %>
                    </div>
                    <div class="form_label">
                        <%= f.label :pepole ,"人数", class:"Required"  %>
                        <%= f.text_field :pepole,class:"input is-link"%>
                    </div>
                    <%= f.hidden_field :user_id, value: current_user.id %>
                    <%= f.hidden_field :id, value: @reservation.id %>
                    <%= f.hidden_field :room_id, value: @reservation.room_id %>
                    <div class="reservation_footer_button">
                        <a href="/reservations"><button type="button" class="button">キャンセル</button></a>
                        <%= f.submit "確認画面へ",class:"button is-link" %>
                    </div>
                <% end %>
            </div>
        </div>
    </section>
</div>

app/views/reservations/edit_confirm.html.erb
<div class="container reservation_form">
  <h2>予約内容の確認</h2>
  <table class="confirm_table">
    <tr>
      <th>チェックイン</th>
      <td><%= @reservation.check_in.strftime('%Y/%m/%d') %></td>
    </tr>
    <tr>
      <th>チェックアウト</th>
      <td><%= @reservation.check_out.strftime('%Y/%m/%d') %></td>
    </tr>
    <tr>
      <th>日数</th>
      <td><%= @reservation.days %></td>
    </tr>
    <tr>
      <th>宿泊人数</th>
      <td><%= @reservation.pepole %></td>
    </tr>
    <tr>
      <th>お支払い金額</th>
      <td>¥<%= @reservation.total_price.to_s(:delimited) %></td>
    </tr>
  </table>
  <p class="cofirm_info">上記内容で正しければ「確定」ボタンを押してください。</p>
  <%= form_with model:@reservation, local: true do |f| %>
    <%= f.hidden_field :check_in, value: @reservation.check_in %>
    <%= f.hidden_field :check_out, value: @reservation.check_out %>
    <%= f.hidden_field :pepole, value: @reservation.pepole %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :room_id, value: @reservation.room_id %>
    <div class="filed">
      <%= f.submit '確定', class: "button is-danger btn" %>
    </div>
    <div class="actions">
      <%= link_to"キャンセル",room_path(@reservation.room_id), class: "button m-t-10 btn"  %>
    </div>
  <% end %>
</div>

app/views/reservations/index.html.erb
<section class="container">
  <h2>予約済み一覧</h2>
  <table class="table is-striped reservation_table list_table">
    <thead>
      <tr>
        <th>画像</th>
        <th>施設名</th>
        <th>紹介文</th>
        <th>合計料金</th>
        <th>チェックイン</th>
        <th>チェックアウト</th>
        <th>予約確定日時</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <% @reservation.each do |reservation|%>
      <tr>
        <td><%= image_tag reservation.room.facility_img.url, size: '100x120' %></td>
        <td><%= link_to reservation.room.facility_name, room_path(reservation.room_id)  %></td>
        <td><%= reservation.room.facility_detail %></td>
        <td>¥<%= reservation.total_price.to_s(:delimited) %></td>
        <td><%= reservation.check_in.strftime('%Y/%m/%d') %></td>
        <td><%= reservation.check_out.strftime('%Y/%m/%d') %></td>
        <td><%= reservation.created_at.strftime('%Y/%m/%d %H:%M') %></td>
        <td>
          <div class="navbar-item has-dropdown is-hoverable" style="margin-right: 100px;">
            <a class="navbar-item"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-three-dots-vertical" viewBox="0 0 16 16">
            <path d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
            </svg></a>
            <div class="navbar-dropdown">
              <%= link_to  "再予約する", [:edit, reservation], class: "navbar-item" %>
              <%= link_to "削除", reservation, method: :delete, data: { confirm: "本当に削除しますか？" }, class: "navbar-item" %>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</section>

app/views/rooms/edit.html.erb
<div class="container">
  <section>
    <div class="form_position">
        <div class="title">
          <h2>施設情報の編集</h2>
        </div> 
        <%= render "shared/error", obj: @room %>
        <div class="register_form">
          <%= form_with model: @room do |f| %>
          <div class="form_label">
            <%= f.label :facility_name ,"施設名", class:"Required" %>
            <%= f.text_field :facility_name,class:"input is-link", placeholder: "ルーム名を入力" %>
          </div>
          <div class="form_label">
            <%= f.label :facility_detail ,"施設詳細", class:"Required"  %>
            <%= f.text_area :facility_detail,class:"input is-link text_area", placeholder: "施設詳細を入力" %>
          </div>
          <div class="form_label">
            <%= f.label :price ,"料金", class:"Required"  %>
            <%= f.text_field :price,class:"input is-link", placeholder: "1日あたりの料金を入力" %>
          </div>
          <div class="form_label">
            <%= f.label :address ,"住所", class:"Required"  %>
            <%= f.text_field :address,class:"input is-link", placeholder: "住所を入力" %>
          </div>
          <div class="form_label">
            <%= f.label :facility_img ,"施設画像" %>
            <%= f.file_field :facility_img,class:"img"%>
          </div>

            <%= f.hidden_field :user_id, value: current_user.id %>
          <div class="footer_button">
            <a href="/rooms/own"><button type="button" class="button">キャンセル</button></a>
            <input type="submit" name="commit" value="登録完了" class="button is-link" data-disable-with="保存" />
          </div>
          <% end %>
        </div>
      </div>
  </section>
</div>

app/views/rooms/index.html.erb
<div class="container">
    <%= render  "shared/search" %>
    <p class="sum"><strong><%= @rooms.count %></strong> 件見つかりました</p>
    <div id="cardlayout-wrap">
        <% @rooms.each do |room| %>
            <section class="card-list">
                <a class="card-link" href='<%= "/rooms/#{room.id}" %>'>
                <figure class="card-figure"><%= image_tag room.facility_img.url %></figure>
                <h2 class="card-title"><%= link_to room.facility_name, room  %></h2>
                <p class="card-text-tax"><%= room.address %></p>
                <p class="card-text-tax2"><%= room.facility_detail %></p>
                    <div class="Room_footer">
                        <p class="room_price search_price">¥<%= room.price.to_s(:delimited) %>〜</p>
                    </div>
                </a>
            </section>
        <% end %>
    </div>
</div>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
  <ul>
    <li class="tag is-warning"><%= message %></li>
  </ul>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar is-light Title_nav" role="navigation" aria-label="main navigation">
    <div class="Title_Header">
        <div class="navbar-brand">
            <a class="navbar-item" href="/">
                <h1>Stay Reserve</h1>
            </a>
        </div>
        <div id="navbarBasicExample" class="navbar-menu nav_aicon">
            <div class="navbar-end">
            <!-- もしログインしていなかったら-->
            <% if (!user_signed_in?) %>
                <div class="navbar-item">
                    <div class="buttons">
                        <%= link_to  "新規ユーザ登録", new_user_registration_path, class: "button is-white" %>
                        <%= link_to  "ログイン", new_user_session_path, class: "button is-white" %>
                    </div>
                </div>
            <!-- ログインしていたら -->
            <% else %>
                <div class="navbar-item has-dropdown is-hoverable" style="margin-right: 100px;">
                    <a class="navbar-item"><%= image_tag current_user.avatar.url %></a>
                    <a class="navbar-item"><%= current_user.full_name %></a>
                    <div class="navbar-dropdown">
                        <%= link_to  "施設の新規登録", :new_room, class: "navbar-item" %>
                        <%= link_to  "予約済み一覧", "/reservations", class: "navbar-item" %>
                        <%= link_to  "登録済み一覧", "/rooms/own", class: "navbar-item" %>
                        <%= link_to  "アカウント設定", account_users_path, class: "navbar-item" %>
                        <a href="" class="navbar-item"></a>
                        <hr class="navbar-divider">
                        <%= link_to  "ログアウト", destroy_user_session_path, method: :delete, class: "navbar-item" %>
                    </div>
                </div>
            <% end %>            
            </div>
        </div>
    </div>
</nav>

app/views/shared/_search.html.erb
<div class="field is-grouped search_form">
    <%= search_form_for @q, url: search_rooms_path,class: "field is-grouped search_form" do |f| %>
    <p class="control">
    <%= f.search_field :address_cont, value: "", class: "input", placeholder: "エリア名を入力" %>
    </p>
    <p class="control">
    <%= f.search_field :facility_name_or_facility_detail_cont, value: "", class: "input", placeholder: "キーワード名を入力" %>
    </p>
    <p class="control">
    <%= f.submit '検索', class: "button is-link is-outlined" %>
    </p>
    <% end %>
</div>

app/views/users/account.html.erb
<section class="container UserSection ">
    <h2>設定</h2>
</section>
<section class="main-content columns is-fullheight">
    <aside class="column is-2 is-narrow-mobile is-fullheight section is-hidden-mobile">
        <ul class="menu-list">
            <li>
                <ul>
                    <li>
                        <%= link_to  "アカウント", account_users_path, class: "navbar-item navbar-account" %>
                    </li>
                    <li>
                        <%= link_to  "プロフィール", profile_users_path, class: "navbar-item" %>
                    </li>
                </ul>
            </li>
        </ul>
    </aside>
    <div class="column is-10">
        <div class="section">
            <div class="section_title">
                <h3>アカウント</h3>
                <a href='<%= "/account" %>'>
                    <button type="button" class="button is-light">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                        <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                        </svg> 編集する
                    </button>
                </a>
            </div>
            <div class="card">
                <div class="card-header">
                    <p class="card-header-title">メールアドレス</p>
                </div>
                <div class="card-content">
                    <div class="content">
                        <%= current_user.email %>
                    </div>
                </div>
            </div>
            <br />
            <div class="card is-hidden1">
                <div class="card-header">
                    <p class="card-header-title">パスワード</p>
                </div>
                <div class="card-content">
                    <div class="content">
                        *********
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/users/home.html.erb
<div class="FirstView">
  <section class="container">
    <h2 class="FirstView_title">
      Stay Reserveで<br>
      まだ体験したことのない<br>
      旅をしよう
    </h2>
    <div class="FirstViewSearch">
      <%= search_form_for @q, url: search_rooms_path do |f| %>
        <%= f.search_field :address_cont, value: "", class: "input", placeholder: "エリア名を入力「東京」など" %>
        <%= f.submit "探す", class: "button is-danger is-light btn_seek", data:{disable_with: "探す"} %>
      <% end %>
    </div>
  </section>
</div>
<div class="container">
  <section class="RecommendAreaSection">
    <h2 class="RecommendAreaSection__title">
      おすすめのエリア
    </h2>
    <div class="RecommendAreas">
    <%= link_to({controller: "rooms", action: "search", q: { address_cont: '東京'}}, { class: "RecommendArea RecommendArea--tokyo"}) do %>
        <span class="RecommendArea__name RecommendArea__name--ja">東京</span>
        <span class="RecommendArea__name RecommendArea__name--en">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
            <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"/>
          </svg>
          Tokyo
        </span>
    <% end %>
    <%= link_to({controller: "rooms", action: "search", q: { address_cont: '大阪'}}, { class: "RecommendArea RecommendArea--osaka"}) do %>
        <span class="RecommendArea__name RecommendArea__name--ja">大阪</span>
        <span class="RecommendArea__name RecommendArea__name--en">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
            <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"/>
          </svg>
          Osaka
        </span>
    <% end %>
    <%= link_to({controller: "rooms", action: "search", q: { address_cont: '京都'}}, { class: "RecommendArea RecommendArea--kyoto"}) do %>
        <span class="RecommendArea__name RecommendArea__name--ja">京都</span>
        <span class="RecommendArea__name RecommendArea__name--en">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
            <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"/>
          </svg>
          Kyoto
        </span>
    <% end %>
    <%= link_to({controller: "rooms", action: "search", q: { address_cont: '札幌'}}, { class: "RecommendArea RecommendArea--sapporo"}) do %>
        <span class="RecommendArea__name RecommendArea__name--ja">札幌</span>
        <span class="RecommendArea__name RecommendArea__name--en">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
            <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"/>
          </svg>
          Sapporo
        </span>
    <% end %>  
    </div>
  </section>
</div>

app/views/users/profile.html.erb
<section class="container UserSection ">
    <h2>設定</h2>
    
</section>
<section class="main-content columns is-fullheight">
    <aside class="column is-2 is-narrow-mobile is-fullheight section is-hidden-mobile">
        <ul class="menu-list">
            <li>
                <ul>
                    <li>
                        <%= link_to  "アカウント", account_users_path, class: "navbar-item" %>
                    </li>
                    <li>
                        <%= link_to  "プロフィール", profile_users_path, class: "navbar-item navbar-profile" %>
                    </li>
                </ul>
            </li>
        </ul>
    </aside>
    <div class="column is-10">
        <div class="section">
            <div class="section_title">
                <h3>プロフィール</h3>
                <a href='<%= "/users/#{current_user.id}/edit" %>'>
                    <button type="button" class="button is-light">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                        <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                        </svg> 編集する
                    </button>
                </a>
            </div>
            <div class="card">
                <div class="card-header">
                    <p class="card-header-title">アイコン画像</p>
                </div>
                <div class="card-content">
                    <div class="content">
                        <%= image_tag current_user.avatar.url %>
                    </div>
                </div>
            </div>
            <br />
            <div class="card is-hidden1">
                <div class="card-header">
                    <p class="card-header-title">名前</p>
                </div>
                <div class="card-content">
                    <div class="content">
                        <%= current_user.full_name %>
                    </div>
                </div>
            </div>
            <br />
            <div class="card is-hidden1">
                <div class="card-header">
                    <p class="card-header-title">自己紹介</p>
                </div>
                <div class="card-content">
                    <div class="content">
                        <%= current_user.introduction %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>